### ISSUE TITLE
Version 1.0 TO-DO

### ISSUE THREAD

**Issue by magnetardev** [ZenithDevs/ControllerKit#1]
**Meta**
- [x] Add a `off` method for unbinding event listeners.
- [x] Revise on change event to either return all states or have some identification of which input source is being handled

**Touch**
- [x] Allow for binding HTML elements to controls (not using the data-ck-control HTML attribute)

**Gamepad**
- [x] Add support for analog sticks

**Keyboard**
- [x] ~~Disable keyboard support if there is no keyboard (not sure if possible)~~ not possible

**Demo**
- [x] Use the CSS safe area env values to support devices with notches.

**Docs**
- [x] Finish documenting things
   - [x] Bindings
   - [x] Event listeners

**Comment by Shugabuga** [comment]
*\*Sorry for the accidental edit. Reverted it.*

**Comment by magnetardev** [comment]
v1 is now done!
